apiVersion: vpc.nddo.yndd.io/v1alpha1
kind: Vpc
metadata:
  name: infra
  namespace: default
spec:
  oda:  
  - key: organization
    value: nokia
  - key: deployment
    value: region1
  vpc:
    defaults:
      tunnel: vxlan
      protocol: evpn
    admin-state: enable
    description: vpc for server infrastructure
    bridge-domains:
    - name: infrastructure
      interface-selector:
      - tag: 
        - {key: kind, value: epg}
        - {key: endpoint-group, value: server-pod1}
        vlan: 40
    routing-tables:
    - name: infrastructure
      tunnel: vxlan
      protocol: evpn
      bridge-domains:
      - name: infrastructure
        ipv4-prefixes: [100.112.3.0/24]
        ipv6-prefixes: [2a02:1800:80:7000::/64]
      interface-selector:
      - tag: 
        - {key: kind, value: epg}
        - {key: endpoint-group, value: dcgw}
        ipv4-prefixes: [100.112.10.0/24]
        ipv6-prefixes: [2a02:1800:80:7050::/64]
        vlan: 40