apiVersion: vpc.nddo.yndd.io/v1alpha1
kind: Vpc
metadata:
  name: vpc-multus
  namespace: default
spec:
  oda:  
  - key: organization
    value: nokia
  - key: deployment
    value: region1
  vpc:
    admin-state: enable
    description: vpc for multus
    registers:
    - {kind: ipam, name: test}
    - {kind: network-instance, name: test}
    - {kind: as, name: deterministic}
    - {kind: vlan, name: test}
    bridge-domains:
    - name: multus-ipvlan
      interface-selector:
      - tag:
        - {key: kind, value: epg}
        - {key: endpoint-group, value: server-pod1}
        - {key: itfce-kind, value: ipvlan}          
        vlan: 100
    - name: multus-sriov1
      interface-selector:
      - tag: 
        - {key: kind, value: epg}
        - {key: endpoint-group, value: server-pod1}
        - {key: itfce-kind, value: sriov1}  
        vlan: 101
    - name: multus-sriov2
      interface-selector:
      - tag: 
        - {key: kind, value: epg}
        - {key: endpoint-group, value: server-pod1}
        - {key: itfce-kind, value: sriov2}  
        vlan: 102
    routing-tables:
    - name: mutlus
      bridge-domains:
      - name: multus-ipvlan
        ipv4-prefixes: [100.112.1.0/24]
        ipv6-prefixes: [2a02:1800:81:7000::/64]
      - name: infrastructure
        ipv4-prefixes: [100.112.2.0/24]
        ipv6-prefixes: [2a02:1800:82:7000::/64]
      - name: infrastructure
        ipv4-prefixes: [100.112.3.0/24]
        ipv6-prefixes: [2a02:1800:83:7000::/64]
      interface-selector:
      - tag: 
        - {key: kind, value: node-itfce}
        - {key: leaf1, value: int-1/1/48}
        ipv4-prefixes: [100.112.10.1/31]
        ipv6-prefixes: [2a02:1800:80:7050::1/64]
        vlan: 10
      - tag: 
        - {key: kind, value: node-itfce}
        - {key: leaf2, value: int-1/1/48}
        ipv4-prefixes: [100.112.10.3/31]
        ipv6-prefixes: [2a02:1800:80:7050::3/64]
        vlan: 11
    
  