//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 NDD.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoVpc) DeepCopyInto(out *NddoVpc) {
	*out = *in
	if in.Vpc != nil {
		in, out := &in.Vpc, &out.Vpc
		*out = make([]*NddoVpcVpc, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoVpcVpc)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoVpc.
func (in *NddoVpc) DeepCopy() *NddoVpc {
	if in == nil {
		return nil
	}
	out := new(NddoVpc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoVpcVpc) DeepCopyInto(out *NddoVpcVpc) {
	*out = *in
	if in.AddressingScheme != nil {
		in, out := &in.AddressingScheme, &out.AddressingScheme
		*out = new(string)
		**out = **in
	}
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.InterfaceTagPool != nil {
		in, out := &in.InterfaceTagPool, &out.InterfaceTagPool
		*out = new(string)
		**out = **in
	}
	if in.IslIpamPool != nil {
		in, out := &in.IslIpamPool, &out.IslIpamPool
		*out = new(string)
		**out = **in
	}
	if in.LoopbackIpamPool != nil {
		in, out := &in.LoopbackIpamPool, &out.LoopbackIpamPool
		*out = new(string)
		**out = **in
	}
	if in.OverlayAsPool != nil {
		in, out := &in.OverlayAsPool, &out.OverlayAsPool
		*out = new(string)
		**out = **in
	}
	if in.OverlayProtocol != nil {
		in, out := &in.OverlayProtocol, &out.OverlayProtocol
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(NddoVpcVpcState)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologyName != nil {
		in, out := &in.TopologyName, &out.TopologyName
		*out = new(string)
		**out = **in
	}
	if in.UnderlayAsPool != nil {
		in, out := &in.UnderlayAsPool, &out.UnderlayAsPool
		*out = new(string)
		**out = **in
	}
	if in.UnderlayProtocol != nil {
		in, out := &in.UnderlayProtocol, &out.UnderlayProtocol
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoVpcVpc.
func (in *NddoVpcVpc) DeepCopy() *NddoVpcVpc {
	if in == nil {
		return nil
	}
	out := new(NddoVpcVpc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoVpcVpcState) DeepCopyInto(out *NddoVpcVpcState) {
	*out = *in
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = new(string)
		**out = **in
	}
	if in.Node != nil {
		in, out := &in.Node, &out.Node
		*out = make([]*NddoVpcVpcStateNode, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoVpcVpcStateNode)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Link != nil {
		in, out := &in.Link, &out.Link
		*out = make([]*NddoVpcVpcStateLink, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoVpcVpcStateLink)
				**out = **in
			}
		}
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoVpcVpcState.
func (in *NddoVpcVpcState) DeepCopy() *NddoVpcVpcState {
	if in == nil {
		return nil
	}
	out := new(NddoVpcVpcState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoVpcVpcStateLink) DeepCopyInto(out *NddoVpcVpcStateLink) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoVpcVpcStateLink.
func (in *NddoVpcVpcStateLink) DeepCopy() *NddoVpcVpcStateLink {
	if in == nil {
		return nil
	}
	out := new(NddoVpcVpcStateLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoVpcVpcStateNode) DeepCopyInto(out *NddoVpcVpcStateNode) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = make([]*NddoVpcVpcStateNodeEndpoint, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoVpcVpcStateNodeEndpoint)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoVpcVpcStateNode.
func (in *NddoVpcVpcStateNode) DeepCopy() *NddoVpcVpcStateNode {
	if in == nil {
		return nil
	}
	out := new(NddoVpcVpcStateNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoVpcVpcStateNodeEndpoint) DeepCopyInto(out *NddoVpcVpcStateNodeEndpoint) {
	*out = *in
	if in.Lag != nil {
		in, out := &in.Lag, &out.Lag
		*out = new(bool)
		**out = **in
	}
	if in.LagSubLink != nil {
		in, out := &in.LagSubLink, &out.LagSubLink
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoVpcVpcStateNodeEndpoint.
func (in *NddoVpcVpcStateNodeEndpoint) DeepCopy() *NddoVpcVpcStateNodeEndpoint {
	if in == nil {
		return nil
	}
	out := new(NddoVpcVpcStateNodeEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Root) DeepCopyInto(out *Root) {
	*out = *in
	if in.InfraNddoVpc != nil {
		in, out := &in.InfraNddoVpc, &out.InfraNddoVpc
		*out = new(NddoVpc)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Root.
func (in *Root) DeepCopy() *Root {
	if in == nil {
		return nil
	}
	out := new(Root)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vpc) DeepCopyInto(out *Vpc) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vpc.
func (in *Vpc) DeepCopy() *Vpc {
	if in == nil {
		return nil
	}
	out := new(Vpc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Vpc) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcList) DeepCopyInto(out *VpcList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Vpc, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcList.
func (in *VpcList) DeepCopy() *VpcList {
	if in == nil {
		return nil
	}
	out := new(VpcList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VpcList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcSpec) DeepCopyInto(out *VpcSpec) {
	*out = *in
	out.ResourceSpec = in.ResourceSpec
	if in.Vpc != nil {
		in, out := &in.Vpc, &out.Vpc
		*out = new(VpcVpc)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcSpec.
func (in *VpcSpec) DeepCopy() *VpcSpec {
	if in == nil {
		return nil
	}
	out := new(VpcSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcStatus) DeepCopyInto(out *VpcStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	if in.VpcName != nil {
		in, out := &in.VpcName, &out.VpcName
		*out = new(string)
		**out = **in
	}
	if in.Vpc != nil {
		in, out := &in.Vpc, &out.Vpc
		*out = new(NddoVpcVpc)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcStatus.
func (in *VpcStatus) DeepCopy() *VpcStatus {
	if in == nil {
		return nil
	}
	out := new(VpcStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcVpc) DeepCopyInto(out *VpcVpc) {
	*out = *in
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.BridgeDomains != nil {
		in, out := &in.BridgeDomains, &out.BridgeDomains
		*out = make([]*VpcVpcBridgedDomains, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(VpcVpcBridgedDomains)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.RoutingTables != nil {
		in, out := &in.RoutingTables, &out.RoutingTables
		*out = make([]*VpcVpcRoutingTables, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(VpcVpcRoutingTables)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	in.Defaults.DeepCopyInto(&out.Defaults)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcVpc.
func (in *VpcVpc) DeepCopy() *VpcVpc {
	if in == nil {
		return nil
	}
	out := new(VpcVpc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcVpcBridgedDomains) DeepCopyInto(out *VpcVpcBridgedDomains) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Tunnel != nil {
		in, out := &in.Tunnel, &out.Tunnel
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	in.InterfaceSelectors.DeepCopyInto(&out.InterfaceSelectors)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcVpcBridgedDomains.
func (in *VpcVpcBridgedDomains) DeepCopy() *VpcVpcBridgedDomains {
	if in == nil {
		return nil
	}
	out := new(VpcVpcBridgedDomains)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcVpcDefaults) DeepCopyInto(out *VpcVpcDefaults) {
	*out = *in
	if in.Tunnel != nil {
		in, out := &in.Tunnel, &out.Tunnel
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcVpcDefaults.
func (in *VpcVpcDefaults) DeepCopy() *VpcVpcDefaults {
	if in == nil {
		return nil
	}
	out := new(VpcVpcDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcVpcRoutingTables) DeepCopyInto(out *VpcVpcRoutingTables) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.BridgeDomains != nil {
		in, out := &in.BridgeDomains, &out.BridgeDomains
		*out = make([]*VpcVpcRoutingTablesBridgeDomains, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(VpcVpcRoutingTablesBridgeDomains)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tunnel != nil {
		in, out := &in.Tunnel, &out.Tunnel
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	in.InterfaceSelectors.DeepCopyInto(&out.InterfaceSelectors)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcVpcRoutingTables.
func (in *VpcVpcRoutingTables) DeepCopy() *VpcVpcRoutingTables {
	if in == nil {
		return nil
	}
	out := new(VpcVpcRoutingTables)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcVpcRoutingTablesBridgeDomains) DeepCopyInto(out *VpcVpcRoutingTablesBridgeDomains) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Ipv4Prefixes != nil {
		in, out := &in.Ipv4Prefixes, &out.Ipv4Prefixes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Ipv6Prefixes != nil {
		in, out := &in.Ipv6Prefixes, &out.Ipv6Prefixes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcVpcRoutingTablesBridgeDomains.
func (in *VpcVpcRoutingTablesBridgeDomains) DeepCopy() *VpcVpcRoutingTablesBridgeDomains {
	if in == nil {
		return nil
	}
	out := new(VpcVpcRoutingTablesBridgeDomains)
	in.DeepCopyInto(out)
	return out
}
